conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: fastmri
  root: ./data/mri_samples/ #move data point from gdrive to this path

measurement:
  operator:
    name: mri_reconstruction
    in_shape: !!python/tuple [1, 1, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.05
